### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jamiehannaford** [Peekmo/JsonPath#6]
Hi, would you mind submitting a new release on Github? The latest commit is #f51947, and I'd like to reference that in my composer file as `~2.0` or something. Thanks!

**Comment by Peekmo** [comment]
The latest commit isn't interesting.

You can have the latest version of the lib with this on your composer.json 
```json
"peekmo/jsonpath": "2.0-ALPHA"
```

The problem is that this version does not work on cli.

**Comment by jamiehannaford** [comment]
:+1 cheers
